/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import Connection.ConnectionFactory;
import classes.Aluno;
import classes.Avaliacao;
import classes.Disciplina;
import classes.Professor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.DisciplinaDAO;
import verificacao.VerificaEmail;
import verificacao.VerificaNome;
/**
 *
 * @author pedro
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
        txtNomeProfessor.setEnabled(false);
        txtEmail.setEnabled(false);
        txtDepartamento.setEnabled(false);
        txtDisciplinaHorario.setEnabled(false);
        btnCancelarProfessor.setEnabled(false);
        btnEditarHorarioProfessor.setEnabled(false);
        btnExcluirProfessor.setEnabled(false);
        btnNovoProfessor.setEnabled(true);
        btnOkEditarHorario.setEnabled(false);
        btnOkProfessor.setEnabled(false);
        btnPesquisarProfessor.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluirDisciplinaProfessor.setEnabled(false);
    }
    
    public void createProfessor (){
        String [] horariosDisciplinas = txtDisciplinaHorario.getText().split(",");
        DisciplinaDAO procuraDisciplina = new DisciplinaDAO();
        int countDisciplinasEncontradas = 0;
        List<Disciplina> listaDisciplinas = procuraDisciplina.read();
        
        if (VerificaNome.verifica(txtNomeProfessor.getText()) && VerificaEmail.verifica(txtEmail.getText())){
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfessores = new javax.swing.JLabel();
        lblNomeProfessor = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblDisciplinas = new javax.swing.JLabel();
        txtNomeProfessor = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtDisciplinaHorario = new javax.swing.JTextField();
        btnPesquisarProfessor = new javax.swing.JButton();
        btnNovoProfessor = new javax.swing.JButton();
        btnExcluirProfessor = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnOkProfessor = new javax.swing.JButton();
        btnCancelarProfessor = new javax.swing.JButton();
        scrlpnlListaDisciplinasHorarios = new javax.swing.JScrollPane();
        listaDisciplinasHorarios = new javax.swing.JList<>();
        lblDisciplinaHorario = new javax.swing.JLabel();
        btnExcluirDisciplinaProfessor = new javax.swing.JButton();
        btnEditarHorarioProfessor = new javax.swing.JButton();
        btnOkEditarHorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProfessores.setText("Professores");

        lblNomeProfessor.setText("Nome:");

        lblEmail.setText("E-mail:");

        lblDepartamento.setText("Departamento:");

        lblDisciplinas.setText("Lista de disciplinas/horários:");

        btnPesquisarProfessor.setText("Pesquisar");

        btnNovoProfessor.setText("Novo");

        btnExcluirProfessor.setText("Excluir");

        btnSalvar.setText("Salvar");

        btnOkProfessor.setText("OK");

        btnCancelarProfessor.setText("Cancelar");

        listaDisciplinasHorarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrlpnlListaDisciplinasHorarios.setViewportView(listaDisciplinasHorarios);

        lblDisciplinaHorario.setText("Adicionar horários/disciplinas:");

        btnExcluirDisciplinaProfessor.setText("Excluir disciplina");

        btnEditarHorarioProfessor.setText("Editar horário");

        btnOkEditarHorario.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPesquisarProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovoProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProfessores)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDepartamento)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDisciplinas)
                                        .addGap(18, 18, 18)
                                        .addComponent(scrlpnlListaDisciplinasHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnOkProfessor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEditarHorarioProfessor)
                                            .addComponent(btnExcluirDisciplinaProfessor)
                                            .addComponent(btnOkEditarHorario)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDisciplinaHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDisciplinaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfessores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProfessor)
                    .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkProfessor))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisciplinas)
                            .addComponent(scrlpnlListaDisciplinasHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesquisarProfessor)
                            .addComponent(btnExcluirProfessor)
                            .addComponent(btnCancelarProfessor)
                            .addComponent(btnNovoProfessor)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluirDisciplinaProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarHorarioProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOkEditarHorario)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisciplinaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDisciplinaHorario))
                        .addGap(0, 97, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProfessor;
    private javax.swing.JButton btnEditarHorarioProfessor;
    private javax.swing.JButton btnExcluirDisciplinaProfessor;
    private javax.swing.JButton btnExcluirProfessor;
    private javax.swing.JButton btnNovoProfessor;
    private javax.swing.JButton btnOkEditarHorario;
    private javax.swing.JButton btnOkProfessor;
    private javax.swing.JButton btnPesquisarProfessor;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDisciplinaHorario;
    private javax.swing.JLabel lblDisciplinas;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeProfessor;
    private javax.swing.JLabel lblProfessores;
    private javax.swing.JList<String> listaDisciplinasHorarios;
    private javax.swing.JScrollPane scrlpnlListaDisciplinasHorarios;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDisciplinaHorario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
