
public class TelaMontarGrade extends javax.swing.JFrame {

    /**
     * Creates new form MontarGrade
     */
    public TelaMontarGrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOfertaDisciplina = new javax.swing.JPanel();
        btnGradeCancelar = new javax.swing.JButton();
        btnGradeProcurar = new javax.swing.JButton();
        btnGradeOk = new javax.swing.JButton();
        lblGradeDisciplina = new javax.swing.JLabel();
        txtGradeDisciplina = new javax.swing.JTextField();
        lblGradeProfessor = new javax.swing.JLabel();
        lblGradeCodigoDisciplina = new javax.swing.JLabel();
        txtGradeProfessor = new javax.swing.JTextField();
        txtGradeCodigoDisciplina = new javax.swing.JTextField();
        cmbSelecionaGrade = new javax.swing.JComboBox<>();
        pnlGrade = new javax.swing.JPanel();
        scrGrade = new javax.swing.JScrollPane();
        tblGrade = new javax.swing.JTable();
        sprGrade = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlOfertaDisciplina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procure a disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 1, 18))); // NOI18N

        btnGradeCancelar.setText("Cancelar");
        btnGradeCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeCancelarActionPerformed(evt);
            }
        });

        btnGradeProcurar.setText("Procurar");

        btnGradeOk.setText("OK");
        btnGradeOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeOkActionPerformed(evt);
            }
        });

        lblGradeDisciplina.setText("Nome da Disciplina:");

        lblGradeProfessor.setText("Nome do Professor:");

        lblGradeCodigoDisciplina.setText("Código da Disciplina:");

        txtGradeCodigoDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeCodigoDisciplinaActionPerformed(evt);
            }
        });

        cmbSelecionaGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Disiciplina" }));

        javax.swing.GroupLayout pnlOfertaDisciplinaLayout = new javax.swing.GroupLayout(pnlOfertaDisciplina);
        pnlOfertaDisciplina.setLayout(pnlOfertaDisciplinaLayout);
        pnlOfertaDisciplinaLayout.setHorizontalGroup(
            pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfertaDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOfertaDisciplinaLayout.createSequentialGroup()
                        .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOfertaDisciplinaLayout.createSequentialGroup()
                                .addComponent(lblGradeProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOfertaDisciplinaLayout.createSequentialGroup()
                                .addComponent(lblGradeCodigoDisciplina)
                                .addGap(6, 6, 6)))
                        .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOfertaDisciplinaLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnGradeProcurar)
                                .addGap(48, 48, 48)
                                .addComponent(btnGradeCancelar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtGradeProfessor)
                            .addComponent(txtGradeCodigoDisciplina)))
                    .addGroup(pnlOfertaDisciplinaLayout.createSequentialGroup()
                        .addComponent(lblGradeDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGradeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(cmbSelecionaGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnGradeOk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlOfertaDisciplinaLayout.setVerticalGroup(
            pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfertaDisciplinaLayout.createSequentialGroup()
                .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeDisciplina)
                    .addComponent(txtGradeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelecionaGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGradeOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeProfessor)
                    .addComponent(txtGradeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeCodigoDisciplina)
                    .addComponent(txtGradeCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlOfertaDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGradeProcurar)
                    .addComponent(btnGradeCancelar))
                .addContainerGap())
        );

        pnlGrade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 0, 18))); // NOI18N

        tblGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrGrade.setViewportView(tblGrade);

        javax.swing.GroupLayout pnlGradeLayout = new javax.swing.GroupLayout(pnlGrade);
        pnlGrade.setLayout(pnlGradeLayout);
        pnlGradeLayout.setHorizontalGroup(
            pnlGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrGrade)
                .addContainerGap())
        );
        pnlGradeLayout.setVerticalGroup(
            pnlGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGradeLayout.createSequentialGroup()
                .addComponent(scrGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprGrade)
                    .addComponent(pnlGrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOfertaDisciplina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOfertaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGradeCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGradeCancelarActionPerformed

    private void txtGradeCodigoDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeCodigoDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradeCodigoDisciplinaActionPerformed

    private void btnGradeOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGradeOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMontarGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMontarGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMontarGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMontarGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMontarGrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGradeCancelar;
    private javax.swing.JButton btnGradeOk;
    private javax.swing.JButton btnGradeProcurar;
    private javax.swing.JComboBox<String> cmbSelecionaGrade;
    private javax.swing.JLabel lblGradeCodigoDisciplina;
    private javax.swing.JLabel lblGradeDisciplina;
    private javax.swing.JLabel lblGradeProfessor;
    private javax.swing.JPanel pnlGrade;
    private javax.swing.JPanel pnlOfertaDisciplina;
    private javax.swing.JScrollPane scrGrade;
    private javax.swing.JSeparator sprGrade;
    private javax.swing.JTable tblGrade;
    private javax.swing.JTextField txtGradeCodigoDisciplina;
    private javax.swing.JTextField txtGradeDisciplina;
    private javax.swing.JTextField txtGradeProfessor;
    // End of variables declaration//GEN-END:variables
}
